### ISSUE TITLE
question: next release 

### ISSUE THREAD

**Issue by surya46584** [aaberg/sql2o#266]
hi, 

what is the time plan for releasing next version 1.6.0?? i am currently evaluating if we can use this for our project needs and starting off with latest version would be great. also wiki points to 1.5.0 documentation, is it available for 1.6.0 somewhere?

thanks.

**Comment by aaberg** [comment]
Hi, there is no time plan for the next release. The code is ready, as there has been very few reported errors on the release candidates. What is still missing, is the documentation. It requires some work to get up to date. 
Since this is a free-time project, I cannot promise any time frame. Until the final release, you can use [sql2o 1.6.0-RC3](http://search.maven.org/#artifactdetails%7Corg.sql2o%7Csql2o-parent%7C1.6.0-RC3%7Cpom)

**Comment by surya46584** [comment]
thanks for the update
