### ISSUE TITLE
UUID dual-way representation problem

### ISSUE THREAD

**Issue by dimzon** [aaberg/sql2o#73]
MSSQL have UNIQUEIDENTIFIER type
ORACLE use RAW[16]
JDBC in/out as byte array

the problem is UUID is not just 16 bytes - it is
DWORDDWORD-WORD-WORD-WORD-WORDDWORDDWORD
so for  MSSQL you must pass|recieve it in little-endian...
ORACLE at other side just store it as RAW data so you doesn't need to play with endianess

**Comment by ftomassetti** [comment]
Any progress on this? I have a postgres db with a UUID and no idea how to use it with sql2o. I get a NPE on ```addParameter("uuid", UUID.randomUUID())```

**Comment by aaberg** [comment]
After the introduction of bidirectional converters, a UUID converter will convert both parameters and results. So the specifics of this issue has been fixed for some time now. The UUID datatype works out of the box for Postgres, without any specific converter. @ftomassetti  I think you have a different error? Check out [this postgres test](https://github.com/aaberg/sql2o/blob/master/extensions/postgres/src/test/java/org/sql2o/extensions/postgres/UUIDTest.java).

Instead of keeping this issue open, I have created new issues to add UUID converters for Oracle, MsSql and DB2.
#195 #196 #197
